
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CiscoWipe(object):
    def setupUi(self, CiscoWipe):
        CiscoWipe.setObjectName("CiscoWipe")
        CiscoWipe.resize(1215, 680)
        self.centralwidget = QtWidgets.QWidget(CiscoWipe)
        self.centralwidget.setObjectName("centralwidget")
        self.techit = QtWidgets.QPushButton(self.centralwidget)
        self.techit.setGeometry(QtCore.QRect(1120, 590, 71, 41))
        self.techit.setObjectName("techit")
        self.asset = QtWidgets.QLineEdit(self.centralwidget)
        self.asset.setGeometry(QtCore.QRect(620, 610, 81, 20))
        self.asset.setText("")
        self.asset.setObjectName("asset")
        self.pallet = QtWidgets.QLineEdit(self.centralwidget)
        self.pallet.setGeometry(QtCore.QRect(790, 610, 113, 20))
        self.pallet.setText("")
        self.pallet.setObjectName("pallet")
        self.grade = QtWidgets.QComboBox(self.centralwidget)
        self.grade.setGeometry(QtCore.QRect(710, 610, 69, 22))
        self.grade.setObjectName("grade")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.process = QtWidgets.QComboBox(self.centralwidget)
        self.process.setGeometry(QtCore.QRect(910, 610, 69, 22))
        self.process.setObjectName("process")
        self.process.addItem("")
        self.process.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 580, 471, 31))
        self.label.setObjectName("label")
        self.compliance = QtWidgets.QComboBox(self.centralwidget)
        self.compliance.setGeometry(QtCore.QRect(990, 610, 101, 22))
        self.compliance.setObjectName("compliance")
        self.compliance.addItem("")
        self.compliance.addItem("")
        self.compliance.addItem("")
        self.compliance.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(900, 10, 301, 541))
        self.textBrowser.setObjectName("textBrowser")
        self.isswitch2 = QtWidgets.QRadioButton(self.centralwidget)
        self.isswitch2.setGeometry(QtCore.QRect(580, 170, 70, 17))
        self.isswitch2.setObjectName("isswitch2")
        self.isasa2 = QtWidgets.QRadioButton(self.centralwidget)
        self.isasa2.setGeometry(QtCore.QRect(580, 210, 70, 17))
        self.isasa2.setObjectName("isasa2")
        self.iswap2 = QtWidgets.QRadioButton(self.centralwidget)
        self.iswap2.setGeometry(QtCore.QRect(580, 150, 70, 17))
        self.iswap2.setObjectName("iswap2")
        self.isrouter2 = QtWidgets.QRadioButton(self.centralwidget)
        self.isrouter2.setGeometry(QtCore.QRect(580, 190, 70, 17))
        self.isrouter2.setObjectName("isrouter2")
        self.disable2 = QtWidgets.QPushButton(self.centralwidget)
        self.disable2.setGeometry(QtCore.QRect(580, 230, 171, 17))
        self.disable2.setObjectName("disable2")
        self.graphic2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphic2.setGeometry(QtCore.QRect(650, 70, 231, 161))
        self.graphic2.setObjectName("graphic2")
        self.graphic1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphic1.setGeometry(QtCore.QRect(80, 80, 231, 161))
        self.graphic1.setObjectName("graphic1")
        self.isrouter1 = QtWidgets.QRadioButton(self.centralwidget)
        self.isrouter1.setGeometry(QtCore.QRect(10, 200, 70, 17))
        self.isrouter1.setObjectName("isrouter1")
        self.isasa1 = QtWidgets.QRadioButton(self.centralwidget)
        self.isasa1.setGeometry(QtCore.QRect(10, 220, 70, 17))
        self.isasa1.setObjectName("isasa1")
        self.isswitch1 = QtWidgets.QRadioButton(self.centralwidget)
        self.isswitch1.setGeometry(QtCore.QRect(10, 180, 70, 17))
        self.isswitch1.setObjectName("isswitch1")
        self.disable1 = QtWidgets.QPushButton(self.centralwidget)
        self.disable1.setGeometry(QtCore.QRect(10, 240, 171, 17))
        self.disable1.setObjectName("disable1")
        self.iswap1 = QtWidgets.QRadioButton(self.centralwidget)
        self.iswap1.setGeometry(QtCore.QRect(10, 160, 70, 17))
        self.iswap1.setObjectName("iswap1")
        self.graphic3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphic3.setGeometry(QtCore.QRect(80, 260, 231, 161))
        self.graphic3.setObjectName("graphic3")
        self.isrouter3 = QtWidgets.QRadioButton(self.centralwidget)
        self.isrouter3.setGeometry(QtCore.QRect(10, 380, 70, 17))
        self.isrouter3.setObjectName("isrouter3")
        self.isasa3 = QtWidgets.QRadioButton(self.centralwidget)
        self.isasa3.setGeometry(QtCore.QRect(10, 400, 70, 17))
        self.isasa3.setObjectName("isasa3")
        self.isswitch3 = QtWidgets.QRadioButton(self.centralwidget)
        self.isswitch3.setGeometry(QtCore.QRect(10, 360, 70, 17))
        self.isswitch3.setObjectName("isswitch3")
        self.disable3 = QtWidgets.QPushButton(self.centralwidget)
        self.disable3.setGeometry(QtCore.QRect(10, 420, 171, 17))
        self.disable3.setObjectName("disable3")
        self.iswap3 = QtWidgets.QRadioButton(self.centralwidget)
        self.iswap3.setGeometry(QtCore.QRect(10, 340, 70, 17))
        self.iswap3.setObjectName("iswap3")
        self.graphics4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphics4.setGeometry(QtCore.QRect(650, 250, 231, 161))
        self.graphics4.setObjectName("graphics4")
        self.isrouter4 = QtWidgets.QRadioButton(self.centralwidget)
        self.isrouter4.setGeometry(QtCore.QRect(580, 370, 70, 17))
        self.isrouter4.setObjectName("isrouter4")
        self.isasa4 = QtWidgets.QRadioButton(self.centralwidget)
        self.isasa4.setGeometry(QtCore.QRect(580, 390, 70, 17))
        self.isasa4.setObjectName("isasa4")
        self.isswitch4 = QtWidgets.QRadioButton(self.centralwidget)
        self.isswitch4.setGeometry(QtCore.QRect(580, 350, 70, 17))
        self.isswitch4.setObjectName("isswitch4")
        self.disable4 = QtWidgets.QPushButton(self.centralwidget)
        self.disable4.setGeometry(QtCore.QRect(580, 410, 171, 17))
        self.disable4.setObjectName("disable4")
        self.iswap4 = QtWidgets.QRadioButton(self.centralwidget)
        self.iswap4.setGeometry(QtCore.QRect(580, 330, 70, 17))
        self.iswap4.setObjectName("iswap4")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(310, 260, 16, 160))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(310, 80, 16, 160))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(880, 70, 16, 160))
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.verticalScrollBar_4 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_4.setGeometry(QtCore.QRect(880, 250, 16, 160))
        self.verticalScrollBar_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_4.setObjectName("verticalScrollBar_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(260, 440, 251, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CiscoWipe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CiscoWipe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 21))
        self.menubar.setObjectName("menubar")
        CiscoWipe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CiscoWipe)
        self.statusbar.setObjectName("statusbar")
        CiscoWipe.setStatusBar(self.statusbar)

        self.retranslateUi(CiscoWipe)
        QtCore.QMetaObject.connectSlotsByName(CiscoWipe)

    def retranslateUi(self, CiscoWipe):
        _translate = QtCore.QCoreApplication.translate
        CiscoWipe.setWindowTitle(_translate("CiscoWipe", "MainWindow"))
        self.techit.setText(_translate("CiscoWipe", "Tech!"))
        self.grade.setItemText(0, _translate("CiscoWipe", "A"))
        self.grade.setItemText(1, _translate("CiscoWipe", "B"))
        self.grade.setItemText(2, _translate("CiscoWipe", "C"))
        self.grade.setItemText(3, _translate("CiscoWipe", "D"))
        self.grade.setItemText(4, _translate("CiscoWipe", "F"))
        self.process.setItemText(0, _translate("CiscoWipe", "Resale"))
        self.process.setItemText(1, _translate("CiscoWipe", "Teardown"))
        self.label.setText(_translate("CiscoWipe", "Asset                    Grade                         Pallet                      Process                  Compliance"))
        self.compliance.setItemText(0, _translate("CiscoWipe", "Tested for Key functions"))
        self.compliance.setItemText(1, _translate("CiscoWipe", "Evaluated and Non-Functioning"))
        self.compliance.setItemText(2, _translate("CiscoWipe", "Tested for Full Functions"))
        self.compliance.setItemText(3, _translate("CiscoWipe", "Specialty Electronics"))
        self.textBrowser.setHtml(_translate("CiscoWipe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#0055ff;\">CiscoWipe!</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Hello and thank you for using CiscoWipe! This is a free tool that helps you tech Cisco products and get them wiped and processed for easy reselling!</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Disclaimer: This product is designed for use at Technocycle Inc, and may not work outside of their network. Please exercise caution when using this product, as you may need to modify aspects of this open-source design if you wish to use the core components of this application elsewhere. </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.isswitch2.setText(_translate("CiscoWipe", "Is Switch"))
        self.isasa2.setText(_translate("CiscoWipe", "Is ASA"))
        self.iswap2.setText(_translate("CiscoWipe", "Is WAP"))
        self.isrouter2.setText(_translate("CiscoWipe", "Is Router"))
        self.disable2.setText(_translate("CiscoWipe", "Disable/disconnect this terminal"))
        self.isrouter1.setText(_translate("CiscoWipe", "Is Router"))
        self.isasa1.setText(_translate("CiscoWipe", "Is ASA"))
        self.isswitch1.setText(_translate("CiscoWipe", "Is Switch"))
        self.disable1.setText(_translate("CiscoWipe", "Disable/disconnect this terminal"))
        self.iswap1.setText(_translate("CiscoWipe", "Is WAP"))
        self.isrouter3.setText(_translate("CiscoWipe", "Is Router"))
        self.isasa3.setText(_translate("CiscoWipe", "Is ASA"))
        self.isswitch3.setText(_translate("CiscoWipe", "Is Switch"))
        self.disable3.setText(_translate("CiscoWipe", "Disable/disconnect this terminal"))
        self.iswap3.setText(_translate("CiscoWipe", "Is WAP"))
        self.isrouter4.setText(_translate("CiscoWipe", "Is Router"))
        self.isasa4.setText(_translate("CiscoWipe", "Is ASA"))
        self.isswitch4.setText(_translate("CiscoWipe", "Is Switch"))
        self.disable4.setText(_translate("CiscoWipe", "Disable/disconnect this terminal"))
        self.iswap4.setText(_translate("CiscoWipe", "Is WAP"))